<Programa> ::= <Cabecera_programa> <bloque>"PUN"



<bloque> ::= <Inicio_de_bloque> <Declar_de_variables_locales> <Declar_de_subprogs> <Sentencias> <Fin_de_bloque>
<Declar_de_subprogs> ::= <Declar_de_subprogs> <Declar_subprog>
	| ""
<Declar_subprog> ::= <Cabecera_subprograma> <bloque>
 	| ""
<Declar_de_variables_locales> ::= <Marca_ini_declar_variables> <Variables_locales> <Marca_fin_declar_variables>
	|""
<Cabecera_programa> ::= "PROGRAM" "IDEN" "PUNCO"
	| ""
<Marca_ini_declar_variables> ::= "VAR"

<Inicio_de_bloque> ::= "BEGIN"
<Fin_de_bloque> ::= "END"
<Variables_locales> ::= <Variables_locales> <Cuerpo_declar_variables>
	| <Cuerpo_declar_variables>
<Cuerpo_declar_variables> ::= <lista_variables> "DOSPUN" "TIPO " "PUNCO"

<Cabecera_subprog> ::= "FUNCION" "IDEN" "PAA" <lista_argumentos> "PAC" "DOSPUN" "TIPO" "PUNCO"

<lista_argumentos> ::= <lista_argumentos> "PUNCO" <Cuerpo_declar_argumentos>
	| <Cuerpo_declar_argumentos>
<Cuerpo_declar_argumentos> ::= <lista_variables> "TIPO"


<Sentencias> ::= <Sentencias> "PUNCO" <Sentencia>
	| <Sentencia>
<Sentencia> ::= <bloque>
	| <sentencia_asignacion>
	| <sentencia_if>
	| <sentencia_while>
	| <sentencia_for>
	| <sentencia_entrada>
	| <sentencia_salida>
	| <sentencia_return>
<sentencia_asignacion> ::= "IDEN""IGUAL"<expresion> 
<sentencia_if> ::= "IF" <expresion> "THEN" <Sentencia> "ELSE" <Sentencia>
	| "IF" <expresion> "THEN" <Sentencia> 
	| "IF" <expresion> "THEN" <Sentencia> <sentencia_elseif> "ELSE" <Sentencia> 
<sentencia_elseif> ::= "ELIF" <Sentencia> <sentencia_elseif> 

<sentencia_while> ::= "WHILE" <expresion> "DO" <Sentencia>
<sentencia_for> ::= "FOR" "IDEN""IGUAL"<expresion> "TO" <expresion> "DO" <Sentencias>

<sentencia_entrada> ::= "ENTRADA" <lista_variables>
<lista_variables> ::= "IDEN"
    | "IDEN" "CO" <lista_variables> 
<sentencia_salida> ::= "SALIDA" <lista_expresiones_o_cadena>

<lista_expresiones_o_cadena> ::= <expresion>
    | <lista_expresiones_o_cadena> "CO" <expresion>
    | "COSIM""FRASE""COSIM""
    | <lista_expresiones_o_cadena> "CO" "COSIM""FRASE""COSIM""

 

<funcion> ::= "IDEN" "PAA" <lista_expresiones> "PAC" 

<lista_expresiones> ::= <expresion>
	| <lista_expresiones> "CO" <expresion>

<sentencia_return> ::= <sentencia_asignacion>
<expresion> ::= "PAA"<expresion>"PAC"
	| "OPUN"<expresion>
	| <expresion>"OPUN"<expresion>
	| <expresion>"OPBI"<expresion>
	| "NOT"<expresion>
	| "IDEN"
	| <constante>
	| <conjunto>
	| <funcion> 


<conjunto> ::= "CORA"<restoConjunto>"CORC"         
<restoConjunto> ::= <expresion> "CO" <restoConjunto>
    | <constante>"PUN2"<constante>
    |<expresion>
	| ""

<constante> ::= "CONS"
	| "CONSEN"