<var> ::= "var" <variables>
<variables> ::= <ident><variable> ":" "set of integer" ";"<variables>
	|<ident><variable> ":" "set of real" ";"<variables>
	|<ident><variable> ":" "set of character" ";"<variables>
	|<ident><variable> ":" "set of boolean" ";"<variables>
	|<ident><variable> ":" "integer" ";"<variables>
	|<ident><variable> ":" "real" ";"<variables>
	|<ident><variable> ":" "character" ";"<variables>
	|<ident><variable> ":" "boolean" ";"<variables>
	|<ident><variable> ":" "set of integer" ";"
	|<ident><variable> ":" "set of real" ";"
	|<ident><variable> ":" "set of character" ";"
	|<ident><variable> ":" "set of boolean" ";"
	|<ident><variable> ":" "integer" ";"
	|<ident><variable> ":" "real" ";"
	|<ident><variable> ":" "character" ";"
	|<ident><variable> ":" "boolean" ";"
<variable> ::= "," <ident><variable>|""



<aEExp> ::= "("<aEExp>")"
	|"+"<aEExp>
	|"-"<aEExp>
	|<aEExp>"+"<aEExp>
	|<aEExp>"-"<aEExp>
	|<aEExp>"*"<aEExp>
	|<aEExp>"/"<aEExp>
	|<ident>
	|<eNum>
<aRExp> ::= "("<aRExp>")"
	|"+"<aRExp>
	|"-"<aRExp>
	|<aRExp>"+"<aRExp>
	|<aRExp>"-"<aRExp>
	|<aRExp>"*"<aRExp>
	|<aRExp>"/"<aRExp>
	|<ident>
	|<rNum>
<lEExp> ::= "("<lEExp>")"
	|<lEExp>">"<lEExp>
	|<lEExp>">="<lEExp>
	|<lEExp>"<"<lEExp>
	|<lEExp>"<="<lEExp>
	|<lEExp>"="<lEExp>
	|<lEExp>"¬="<lEExp>
	|<lEExp>"<>"<lEExp>
	|<ident>
	|<rNum>
<lRExp> ::= "("<lRExp>")"
	|<lRExp>">"<lRExp>
	|<lRExp>">="<lRExp>
	|<lRExp>"<"<lRExp>
	|<lRExp>"<="<lRExp>
	|<lRExp>"="<lRExp>
	|<lRExp>"¬="<lRExp>
	|<lRExp>"<>"<lRExp>
	|<ident>
	|<rNum>
<bExp> ::= <bExp>"and"<bExp>
	|<bExp>"or"<bExp>
	|<bExp>"xor"<bExp>
	|"not"<bExp>

<ident> ::= <car><identR>
	|"_"<identR>
<identR> ::= <identR><dig>
	|<identR><car>
	|<dig>
	|<car>

<cEntero> ::= "<sent0>"
<cEntInicial> ::= <eNum><enteros>|""
<enteros> ::= "," <eNum><enteros>|""

<cReal> ::= "<sent1>"
<cReInicial> ::= <rNum><reales>|""
<reales> ::= "," <rNum><reales>|""

<cCaracter> ::= "<sent2>"
<cCarInicial> ::= <caracter><caracteres>|""
<caracteres> ::= "," <caracter><caracteres>|""

<eNum> ::= <eNum><dig>
	|<dig>
<rNum> ::= <eNum>"."<eNum>
<caracter> ::= '"'<car>'"'|"'"<car>"'"

<dig> ::= "0"|"1"|"2"|"3"|"4"|"5"|"6"|"7"|"8"|"9"
<car> ::= "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"
	|"n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z"
	|"A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"
	|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z"
<booleano> ::= "true"|"false"<sent0> :=" <cEntInicial> " |.
<sent1> :=" <cEntInicial> "" <cReInicial> " |.
<sent2> :=" <cEntInicial> "" <cReInicial> "" <cCarInicial> " |.
